### PR TITLE
issues/31 Fix popOver hide before display has finished operations

### LINKED ISSUE #31: Android: Hide method does not work if navigation performed by Service.
This issue below happens on anything above `0.1.0` of this plugin, I tested this by stepping through every version and found mixed results of the indicator not working at all or being in this stuck state for Android.

### Which platform(s) does your issue occur on?
- iOS/Android/Both: Android
- iOS/Android versions: 8.0, 8.1, 9.0, 10.0
- emulator or device: All

### Please, provide the following version numbers that your issue occurs with:
- CLI: 6.3.3
- Cross-platform modules: 6.3.2
- Runtime(s): 
```json
"tns-android": {
	"version": "6.3.1"
},
"tns-ios": {
	"version": "6.3.0"
}
```
- Plugin(s):
```json
"dependencies": {
	"@angular/animations": "~8.2.0",
	"@angular/common": "~8.2.0",
	"@angular/compiler": "~8.2.0",
	"@angular/core": "~8.2.0",
	"@angular/forms": "~8.2.0",
	"@angular/platform-browser": "~8.2.0",
	"@angular/platform-browser-dynamic": "~8.2.0",
	"@angular/router": "~8.2.0",
	"@nativescript/theme": "~2.2.1",
	"@nstudio/nativescript-loading-indicator": "^3.0.1",
	"nativescript-angular": "~8.20.3",
	"reflect-metadata": "~0.1.12",
	"rxjs": "^6.4.0",
	"tns-core-modules": "~6.3.0",
	"zone.js": "~0.9.1"
},
"devDependencies": {
	"@angular/compiler-cli": "~8.2.0",
	"@ngtools/webpack": "~8.2.0",
	"nativescript-dev-webpack": "~1.4.0",
	"prettier": "^1.19.1",
	"typescript": "~3.5.3"
},
```

### Please, tell us how to recreate the issue in as much detail as possible. 
Create a basic wrapper service for the Loading Indicator:
```ts
@Injectable()
export class LoadingIndicatorService {
	private isShowing = false;
	private loadingIndicator: LoadingIndicator;

	constructor() {
		this.loadingIndicator = new LoadingIndicator();
	}

	public show(message?: string) {
		if (this.isShowing) {
			return;
		}
		const options: OptionsCommon = {
			message: message,
			dimBackground: true,
			color: '#000000',
			mode: Mode.Indeterminate,
			android: {
				cancelable: false,
			},
			ios: {
				square: false,
			},
		};
		this.loadingIndicator.show(options);
		this.isShowing = true;
	}

	public hide() {
		this.loadingIndicator.hide();
		this.isShowing = false;
	}
}
```
Create a basic service to complete navigation called by a page:
```ts
@Injectable()
export class TestNavService {
	constructor(
		private loadingIndicatorService: LoadingIndicatorService,
		private nav: RouterExtensions
	) {}

	public async tryNav() {
		try {
			await this.nav.navigate(['/page-two-page']);
		} catch (error) {
			console.error(error);
		} finally {
			this.loadingIndicatorService.hide();
		}
	}
}
```

Then on a simple button have a method that starts the loading indicator, then calls the navigation service's method to navigate and hide the loading indicator:
```ts
public onPress() {
	this.loadingIndicatorService.show("This should go away on the next page");
	this.testNavService.tryNav();
}
```

When navigation completed, the `finally` calls the `hide` method on the Loading Indicator Service but on Android the Loading Indicator does not hide. This works perfectly on iOS. If I revert to `0.1.0` this works again as expected, but it's not ideal to use this old version.

### Is there any code involved? 
I have created a basic application reproducing the issue here: https://github.com/Codex-/loading-activity-bug-sample
`tns run ios` will show that it works as expected (you can sleep the hide if you find it's too fast)
`tns run android` will show you the issue described.

### PR DESCRIPTION
**Pull request by Codex-**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] All existing tests are passing
- [ ] Tests for the changes are included

Existing test cases validate existing behaviour is not broken, however to test the race condition completely I can add the sample I provided in the issue I raised.

## What is the current behavior?

The current behaviour when creating a popOver on Android is to launch the creation of the popOver in a `setTimeout`, this means that if you attempt to hide the loading indicator before the operations in the setTimeout have completed then the hide fails (leaving the loading indicator stuck).

## What is the new behavior?

These changes simply introduce an internal creation status to prevent hiding from operating before the creation reference has been stored in the `_loadersInstances` collection. If a hide is attempted when the status is not resolved, it will wait until the `_isCreatingPopOver` property is false. This is also safe guarded with a default hide attempt timeout of 1000ms (this is a parameter of `hide`).

Fixes/Closes #31 

No breaking changes have been made here.

### CODE REVIEW

**Comment by Codex-** [comment]
CI failed with `npm ERR! 429 Too Many Requests - GET https://registry.npmjs.org/tslint`

Might want to kick it off again :)

**Comment by Codex-** [comment]
I think this is ready for review now. Updated the method signature to be cross compatible with the `hide` method in iOS.

Updated the exported typings to have the correct signature for `hide` for both iOS and Android.

This should prevent existing implementations that use `hide` with a targetView for iOS from breaking.

**Comment by bradmartin** [comment]
I'll try to look at this tomorrow, thanks for helping work on this. I had a discussion with @NathanWalker other day about the entire `timeout` step being added to keep track of the loading indicators internally. He was encountering issues with various services I believe in a complex ng app. He was removing the timeout locally to see how things behaved and mentioned simplifying things a bit. 

What we might do, is go ahead and bump this with your PR changes, initial quick look appears fine. Then if issues continue, we can try a beta release with Nathan's approach for you and others who have encountered race conditions to use for a bit before we go main with it 🤔or vice versa (getting late for me).

**Comment by Codex-** [comment]
Thanks @bradmartin, happy to help design other solutions too. I suspect there are a few race conditions in the android implementation when rendering options but haven't had time to experiment with those. Would be good to get this in though for now

**Pull request merged**
